"""GitHub Issue 提交模块：使用 gh CLI 提交审查结果为 Issue"""

import subprocess
import shutil
import json
from datetime import datetime
from typing import Optional

from .config import Config


def _get_gh_executable() -> str:
    """获取 gh 可执行文件路径，优先用完整路径以避免 PATH 问题"""
    gh_path = shutil.which("gh")
    if gh_path:
        return gh_path
    # Windows 常见安装路径兜底
    import os
    fallback = r"C:\Program Files\GitHub CLI\gh.exe"
    if os.path.isfile(fallback):
        return fallback
    return "gh"   # 最后兜底


def _run_gh(args: list[str], input_text: Optional[str] = None) -> subprocess.CompletedProcess:
    """运行 gh CLI 命令"""
    result = subprocess.run(
        [_get_gh_executable()] + args,
        input=input_text,
        capture_output=True,
        text=True,
        encoding="utf-8",
    )
    return result


def check_gh_auth() -> bool:
    """检查 gh 是否已登录"""
    result = _run_gh(["auth", "status"])
    return result.returncode == 0


def get_repo_info(repo: str) -> dict:
    """获取仓库信息"""
    result = _run_gh(["repo", "view", repo, "--json",
                      "name,description,defaultBranchRef,stargazerCount,isPrivate"])
    if result.returncode != 0:
        return {}
    try:
        return json.loads(result.stdout)
    except Exception:
        return {}


def build_issue_body(
    repo: str,
    summary: str,
    batch_reviews: list[str],
    file_count: int,
    config: Config,
    include_details: bool = True,
) -> str:
    """构建 Issue 正文 Markdown"""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    if config.review_language == "zh":
        header = f"""> 🤖 本 Issue 由 **AutoIssue** 自动生成 | 生成时间：{now}
> 仓库：`{repo}` | 审查文件数：{file_count} | 模型：`{config.model}`

---

"""
        details_title = "## 📋 各批次详细审查记录"
        details_note = "以下是按批次划分的详细审查记录，供参考："
        batch_label = "### 第 {i} 批"
        footer = """

---

> *此报告由 [AutoIssue](https://github.com) 工具自动生成，请结合实际情况判断问题的优先级。*"""
    else:
        header = f"""> 🤖 This Issue was automatically generated by **AutoIssue** | Generated at: {now}
> Repository: `{repo}` | Files reviewed: {file_count} | Model: `{config.model}`

---

"""
        details_title = "## 📋 Detailed Review by Batch"
        details_note = "The following are detailed review records organized by batch:"
        batch_label = "### Batch {i}"
        footer = """

---

> *This report was automatically generated by [AutoIssue](https://github.com). Please use your judgment to prioritize the issues.*"""

    body = header + summary

    if include_details and batch_reviews:
        # 只附上有问题的批次
        meaningful = [
            (i + 1, r) for i, r in enumerate(batch_reviews)
            if "无明显问题" not in r and "no significant issues" not in r.lower()
        ]
        if meaningful:
            body += f"\n\n{details_title}\n\n{details_note}\n\n"
            body += "\n\n".join(
                f"{batch_label.format(i=i)}\n\n{r}"
                for i, r in meaningful
            )

    body += footer
    return body


def create_issue(
    repo: str,
    title: str,
    body: str,
    labels: Optional[list[str]] = None,
    dry_run: bool = False,
) -> Optional[str]:
    """
    在指定仓库创建 Issue。
    返回创建成功的 Issue URL，失败返回 None。
    dry_run=True 时只打印内容不实际创建。
    """
    if dry_run:
        print("\n" + "=" * 60)
        print(f"[DRY RUN] 将创建 Issue：")
        print(f"  仓库: {repo}")
        print(f"  标题: {title}")
        if labels:
            print(f"  标签: {', '.join(labels)}")
        print(f"\n--- Issue 正文 ---\n{body}\n" + "=" * 60)
        return None

    args = [
        "issue", "create",
        "--repo", repo,
        "--title", title,
        "--body", body,
    ]

    if labels:
        # 尝试使用标签（标签必须提前在仓库中创建）
        args += ["--label", ",".join(labels)]

    print(f"  正在提交 Issue 到 {repo} ...")
    result = _run_gh(args)

    if result.returncode != 0:
        err = result.stderr.strip()
        # 如果是标签不存在的错误，去掉标签重试
        if "label" in err.lower() and labels:
            print(f"  [警告] 标签不存在，将不附加标签重试...")
            args_no_label = [a for a in args if a not in ["--label", ",".join(labels)]]
            result = _run_gh(args_no_label)
            if result.returncode != 0:
                raise RuntimeError(f"创建 Issue 失败：{result.stderr.strip()}")
        else:
            raise RuntimeError(f"创建 Issue 失败：{err}")

    url = result.stdout.strip()
    print(f"  ✅ Issue 创建成功：{url}")
    return url


def submit_review_as_issue(
    repo: str,
    summary: str,
    batch_reviews: list[str],
    file_count: int,
    config: Config,
    dry_run: bool = False,
) -> Optional[str]:
    """完整流程：构建并提交审查 Issue"""
    now_str = datetime.now().strftime("%Y-%m-%d")
    title = f"{config.issue_title_prefix} 代码审查报告 ({now_str})"
    if config.review_language == "en":
        title = f"{config.issue_title_prefix} Code Review Report ({now_str})"

    body = build_issue_body(
        repo=repo,
        summary=summary,
        batch_reviews=batch_reviews,
        file_count=file_count,
        config=config,
    )

    return create_issue(
        repo=repo,
        title=title,
        body=body,
        labels=config.issue_labels,
        dry_run=dry_run,
    )
